// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sn_tool.Shared.Data
{
    public partial class ImportLog
    {
        public int Id { get; set; }
        public DateTime DataLog { get; set; }
       
        public string Operation { get; set; }
        public string Plant { get; set; }
        public string FileName { get; set; }
        public string ProductGroup { get; set; }
       
    }
}