// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sn_tool.Shared.Data
{
    public partial class Sn
    {
        public string SerialNumber { get; set; }
        public string Material { get; set; }
        public DateTime? DateScanned { get; set; }
        public string SalesOrganisation { get; set; }
        public string ShiptoNumber { get; set; }
        public string ShiptoName { get; set; }
        public string ShiptoAddress { get; set; }
        public string Warehouse { get; set; }
        public string WarehouseName { get; set; }
        public string SapdeliveryNumber { get; set; }
        public string SoldtoNumber { get; set; }
        public string SoldtoName { get; set; }
        public int? FileId { get; set; }
        public string PalletId { get; set; }
        public int Id { get; set; }
    }
}