// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sn_tool.Shared.Data
{
    public partial class SnMNT
    {
        public string GoodsIssueDate { get; set; }
        public string Plant { get; set; }
        public string DN { get; set; }
        public string ShipToName { get; set; }
        public string PartNumber { get; set; }
        public string SerialNumber { get; set; }
       
        public string FileName { get; set; }
        public int ID { get; set; }
    }
}