// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Sn_tool.Shared.Data;
using Sn_tool.Shared;

namespace Sn_tool.Server.Data
{
    public partial class TMSContext : DbContext
    {
        public TMSContext()
        {
        }

        public TMSContext(DbContextOptions<TMSContext> options)
            : base(options)
        {
        }


        public virtual DbSet<Sn> Sn_TV { get; set; }

        public virtual DbSet<VTVDailyquatitySn> VTVDailyquatitySn { get; set; }

        public virtual DbSet<VMNTDailyquantitySn> VMNTDailyquantitySn { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<VMNTDailyquantitySn>(entity =>
            {
                entity.HasNoKey();

            });



            modelBuilder.Entity<VTVDailyquatitySn>(entity =>
            {
                entity.HasNoKey();

            });


            modelBuilder.Entity<Sn>(entity =>
            {
                entity.ToTable("SN_TV");

                entity.Property(e => e.DateScanned).HasColumnType("datetime");

                entity.Property(e => e.FileId).HasColumnName("FileID");

                entity.Property(e => e.Material)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PalletId)
                    .HasColumnName("PalletID")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SalesOrganisation)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SapdeliveryNumber)
                    .HasColumnName("SAPDeliveryNumber")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SerialNumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ShiptoAddress)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.ShiptoName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.ShiptoNumber)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.SoldtoName)
                    .HasMaxLength(350)
                    .IsUnicode(false);

                entity.Property(e => e.SoldtoNumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Warehouse)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.WarehouseName)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<Sn_tool.Shared.Data.SnMNT> Sn_MNT { get; set; }

        public DbSet<Sn_tool.Shared.Data.ImportLog> ImportLog { get; set; }
    }
}